language: ruby

rvm:
  - 2.0.0
  - 2.1.8
  - 2.2.4
  - 2.3.0
  - ruby-head
  - jruby-19mode
  - jruby-9.0.4.0
  - jruby-head

os:
  - linux
  - osx

sudo: false

branches:
  only:
    - master

gemfile:
  - Gemfile

matrix:
  allow_failures:
    - rvm: 2.3.0
      os: osx
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: jruby-19mode
      os: osx
    - rvm: rbx-2
